### ISSUE TITLE
jaeger exporter

### ISSUE THREAD

**Issue by HaroonSaid** [ericksoen/opentelemetry-examples#55]

**Comment by ericksoen** [comment]
I see the issue was already closed but I'm going to leave some notes here in case anyone asks for something similar at a later point:

>  We would like to use AWS image, our use case is Linux and Windows Containers that emit otel and jaeger spans.
> We want to export metrics to AWS Managed Prometheus.
> We want to use our own Jeager Infra with Kafka and Open Search. Do you have any plans to support the jaeger exporter?
> If not, what is the best was to use the open-source image to export metrics to AWS Prometheus

Here's the list of current exporters supported by the [AWS Distro](https://github.com/aws-observability/aws-otel-collector#adot-collector-built-in-components) (the `jaegerexporter` is not one of them so you'd have to use an alternative method.

This repository previously used a [custom built container definition](https://github.com/ericksoen/opentelemetry-examples/commit/4af422f3414159c659ec5d12b7cc2a50560149b0#diff-ca2450cf838b1f707270cd69518967704db0a0a3b248e107beb7ca01ca28c571)  prior to converting to the AWS Distro. **This would allow you to use any OTEL supported receivers, extensions, exporters (including those that aren't currently supported by the AWS distro).** The tradeoff is that you now have to build and manage your own container definition (some of the other AWS container behaviors like resolving an OTEL collector config via an enviroment variable (via SSM parameter).

I don't have a working example merged into this repo, but did experiment with some of the AWS Managed Prometheus (AMP) functionality described [here](https://aws-otel.github.io/docs/getting-started/prometheus-remote-write-exporter#aws-prometheus-remote-write-exporter).
